vich_uploader:
  db_driver: orm

  mappings:
    workshops_image:
      uri_prefix: /images/workshops
      upload_destination: "%kernel.project_dir%/public/images/workshops"

    article_image:
      uri_prefix: /images/articles
      upload_destination: "%kernel.project_dir%/public/images/articles"

    book_image:
      uri_prefix: /images/books
      upload_destination: "%kernel.project_dir%/public/images/books"

    product_image:
      uri_prefix: /images/product
      upload_destination: "%kernel.project_dir%/public/images/product"
